// <auto-generated />
using System;
using HeroRPG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeroRPG.Data.Migrations
{
    [DbContext(typeof(HeroRPG_DbContext))]
    partial class HeroRPG_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeroRPG.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RaceID")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceID");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Constitution = 8,
                            Description = "A quick-footed scout.",
                            Dexterity = 15,
                            Name = "Arlen Swift",
                            RaceID = 2,
                            Strength = 10
                        },
                        new
                        {
                            Id = 2,
                            Constitution = 14,
                            Description = "Stout warrior and miner.",
                            Dexterity = 8,
                            Name = "Borin Stonehelm",
                            RaceID = 3,
                            Strength = 16
                        },
                        new
                        {
                            Id = 3,
                            Constitution = 12,
                            Description = "Fearsome berserker.",
                            Dexterity = 9,
                            Name = "Thora Ironfist",
                            RaceID = 4,
                            Strength = 18
                        },
                        new
                        {
                            Id = 4,
                            Constitution = 10,
                            Description = "Clever trickster.",
                            Dexterity = 16,
                            Name = "Lysa Meadow",
                            RaceID = 5,
                            Strength = 8
                        },
                        new
                        {
                            Id = 5,
                            Constitution = 13,
                            Description = "Knight of the realm.",
                            Dexterity = 12,
                            Name = "Sir Gareth",
                            RaceID = 1,
                            Strength = 14
                        },
                        new
                        {
                            Id = 6,
                            Constitution = 9,
                            Description = "Archer and herbalist.",
                            Dexterity = 14,
                            Name = "Mira Greenleaf",
                            RaceID = 2,
                            Strength = 9
                        },
                        new
                        {
                            Id = 7,
                            Constitution = 15,
                            Description = "Defender of the halls.",
                            Dexterity = 9,
                            Name = "Torik Broadshield",
                            RaceID = 3,
                            Strength = 15
                        },
                        new
                        {
                            Id = 8,
                            Constitution = 11,
                            Description = "Headsnatcha extraordinaire.",
                            Dexterity = 10,
                            Name = "Orin Blacktusk",
                            RaceID = 4,
                            Strength = 17
                        });
                });

            modelBuilder.Entity("HeroRPG.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstitutionModifier")
                        .HasColumnType("int");

                    b.Property<int>("DexterityModifier")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StrengthModifier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConstitutionModifier = 1,
                            DexterityModifier = 1,
                            Name = "Human",
                            StrengthModifier = 1
                        },
                        new
                        {
                            Id = 2,
                            ConstitutionModifier = -1,
                            DexterityModifier = 3,
                            Name = "Elf",
                            StrengthModifier = 0
                        },
                        new
                        {
                            Id = 3,
                            ConstitutionModifier = 2,
                            DexterityModifier = -1,
                            Name = "Dwarf",
                            StrengthModifier = 2
                        },
                        new
                        {
                            Id = 4,
                            ConstitutionModifier = 1,
                            DexterityModifier = -1,
                            Name = "Orc",
                            StrengthModifier = 3
                        },
                        new
                        {
                            Id = 5,
                            ConstitutionModifier = -1,
                            DexterityModifier = 4,
                            Name = "Halfling",
                            StrengthModifier = -1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentyUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityUserClaims");
                });

            modelBuilder.Entity("HeroRPG.Models.Hero", b =>
                {
                    b.HasOne("HeroRPG.Models.Race", "Race")
                        .WithMany("Heroes")
                        .HasForeignKey("RaceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("HeroRPG.Models.Race", b =>
                {
                    b.Navigation("Heroes");
                });
#pragma warning restore 612, 618
        }
    }
}
